---

# Project Information
site_name: "Playground"
site_description: Automated deployer of OpenShift cluster and IBM Cloud Paks
site_author: "Author"

nav:
  - Home: index.md
  - 'Unit testing': ./unit-testing.md
  - 'Architecture': ./page2.md
# Theme
theme:
  name: material
  palette:
    scheme: slate
  prev_next_buttons_location: bottom
  collapse_navigation: False
  sticky_navigation: True
  titles_only: True
  features:
    - navigation.expand
  # - css/toolkit-code.css
# Plugins
plugins:
  - search


